# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a98bdc7cf8927b55900e957f723b13c6062eb04e4295d9b744b9567230927dad79e1282831bfc5b95da3de321cba8c8d7d769d99488bc8cf21c3f60392b9046d

test:
  secret_key_base: 80d00ac7af5c3f03ec872bb78c4e177f7bfc76e1d34d5c4b94f49030721206ab23fffd8e55ac0523165b6e9a82587cc0172a190c589cba0aa9c110a8e336f569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
